"""Add company tenancy foundation

Revision ID: 0ec247c60326
Revises: a53169721a16
Create Date: 2026-08-03 16:41:18.249605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec247c60326'
down_revision: Union[str, Sequence[str], None] = 'a53169721a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Company',
    sa.Column('CompanyId', sa.Integer(), nullable=False),
    sa.Column('CompanyCode', sa.String(length=50), nullable=False),
    sa.Column('CompanyName', sa.String(length=150), nullable=False),
    sa.Column('TaxNumber', sa.String(length=20), nullable=True),
    sa.Column('Address', sa.Text(), nullable=True),
    sa.Column('EMail', sa.String(length=100), nullable=True),
    sa.Column('IsActive', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('RecordDate', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('CompanyId'),
    sa.UniqueConstraint('CompanyCode'),
    sa.UniqueConstraint('TaxNumber')
    )
    with op.batch_alter_table('Company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Company_CompanyId'), ['CompanyId'], unique=False)

    company_table = sa.table(
        "Company",
        sa.column("CompanyId", sa.Integer()),
        sa.column("CompanyCode", sa.String()),
        sa.column("CompanyName", sa.String()),
        sa.column("TaxNumber", sa.String()),
        sa.column("Address", sa.Text()),
        sa.column("EMail", sa.String()),
        sa.column("IsActive", sa.Boolean()),
    )

    op.bulk_insert(
        company_table,
        [
            {
                "CompanyId": 1,
                "CompanyCode": "LEGACY",
                "CompanyName": "Mevcut Firma",
                "TaxNumber": None,
                "Address": None,
                "EMail": None,
                "IsActive": True,
            }
        ],
    )

    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CompanyId', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_Customer_CompanyId'), ['CompanyId'], unique=False)
        batch_op.create_foreign_key("fk_Customer_CompanyId_Company", 'Company', ['CompanyId'], ['CompanyId'])

    with op.batch_alter_table('Invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CompanyId', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_Invoice_CompanyId'), ['CompanyId'], unique=False)
        batch_op.create_foreign_key("fk_Invoice_CompanyId_Company", 'Company', ['CompanyId'], ['CompanyId'])

    with op.batch_alter_table('InvoiceLine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CompanyId', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_InvoiceLine_CompanyId'), ['CompanyId'], unique=False)
        batch_op.create_foreign_key("fk_InvoiceLine_CompanyId_Company", 'Company', ['CompanyId'], ['CompanyId'])

    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CompanyId', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_Product_CompanyId'), ['CompanyId'], unique=False)
        batch_op.create_foreign_key("fk_Product_CompanyId_Company", 'Company', ['CompanyId'], ['CompanyId'])

    with op.batch_alter_table('Profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CompanyId', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_Profile_CompanyId'), ['CompanyId'], unique=False)
        batch_op.create_foreign_key("fk_Profile_CompanyId_Company", 'Company', ['CompanyId'], ['CompanyId'])

    with op.batch_alter_table('ProfileRole', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CompanyId', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ProfileRole_CompanyId'), ['CompanyId'], unique=False)
        batch_op.create_foreign_key("fk_ProfileRole_CompanyId_Company", 'Company', ['CompanyId'], ['CompanyId'])

    with op.batch_alter_table('Role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CompanyId', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_Role_CompanyId'), ['CompanyId'], unique=False)
        batch_op.create_foreign_key("fk_Role_CompanyId_Company", 'Company', ['CompanyId'], ['CompanyId'])

    with op.batch_alter_table('UserProfile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CompanyId', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_UserProfile_CompanyId'), ['CompanyId'], unique=False)
        batch_op.create_foreign_key("fk_UserProfile_CompanyId_Company", 'Company', ['CompanyId'], ['CompanyId'])

    with op.batch_alter_table("Users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("CompanyId", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("IsSuperAdmin",sa.Boolean(), server_default="0",nullable=False,))
        batch_op.add_column(sa.Column("IsActive",sa.Boolean(),server_default="1",nullable=False,))
        batch_op.create_index(batch_op.f("ix_Users_CompanyId"),["CompanyId"],unique=False,)
        batch_op.create_foreign_key("fk_Users_CompanyId_Company","Company",["CompanyId"],["CompanyId"],)

    tenant_tables = [
        "Users",
        "Customer",
        "Product",
        "Invoice",
        "InvoiceLine",
        "Profile",
        "Role",
        "ProfileRole",
        "UserProfile",
    ]

    for table_name in tenant_tables:
        op.execute(
            sa.text(
                f'UPDATE "{table_name}" '
                'SET "CompanyId" = 1 '
                'WHERE "CompanyId" IS NULL'
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint("fk_Users_CompanyId_Company", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_Users_CompanyId'))
        batch_op.drop_column('IsActive')
        batch_op.drop_column('IsSuperAdmin')
        batch_op.drop_column('CompanyId')

    with op.batch_alter_table('UserProfile', schema=None) as batch_op:
        batch_op.drop_constraint("fk_UserProfile_CompanyId_Company", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_UserProfile_CompanyId'))
        batch_op.drop_column('CompanyId')

    with op.batch_alter_table('Role', schema=None) as batch_op:
        batch_op.drop_constraint("fk_Role_CompanyId_Company", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_Role_CompanyId'))
        batch_op.drop_column('CompanyId')

    with op.batch_alter_table('ProfileRole', schema=None) as batch_op:
        batch_op.drop_constraint("fk_ProfileRole_CompanyId_Company", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ProfileRole_CompanyId'))
        batch_op.drop_column('CompanyId')

    with op.batch_alter_table('Profile', schema=None) as batch_op:
        batch_op.drop_constraint("fk_Profile_CompanyId_Company", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_Profile_CompanyId'))
        batch_op.drop_column('CompanyId')

    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.drop_constraint("fk_Product_CompanyId_Company", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_Product_CompanyId'))
        batch_op.drop_column('CompanyId')

    with op.batch_alter_table('InvoiceLine', schema=None) as batch_op:
        batch_op.drop_constraint("fk_InvoiceLine_CompanyId_Company", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_InvoiceLine_CompanyId'))
        batch_op.drop_column('CompanyId')

    with op.batch_alter_table('Invoice', schema=None) as batch_op:
        batch_op.drop_constraint("fk_Invoice_CompanyId_Company", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_Invoice_CompanyId'))
        batch_op.drop_column('CompanyId')

    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.drop_constraint("fk_Customer_CompanyId_Company", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_Customer_CompanyId'))
        batch_op.drop_column('CompanyId')

    with op.batch_alter_table('Company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Company_CompanyId'))

    op.drop_table('Company')
    # ### end Alembic commands ###
