"""Create initial schema

Revision ID: a53169721a16
Revises: 
Create Date: 2026-08-03 16:22:52.159773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a53169721a16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(length=50), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('RecordDate', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('UserId')
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Users_UserId'), ['UserId'], unique=False)

    op.create_table('Customer',
    sa.Column('CustomerId', sa.Integer(), nullable=False),
    sa.Column('TaxNumber', sa.String(length=20), nullable=True),
    sa.Column('Title', sa.String(length=100), nullable=False),
    sa.Column('Address', sa.Text(), nullable=True),
    sa.Column('EMail', sa.String(length=100), nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('RecordDate', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], ),
    sa.PrimaryKeyConstraint('CustomerId')
    )
    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Customer_CustomerId'), ['CustomerId'], unique=False)

    op.create_table('Product',
    sa.Column('ProductId', sa.Integer(), nullable=False),
    sa.Column('ProductCode', sa.String(length=50), nullable=True),
    sa.Column('ProductName', sa.String(length=100), nullable=False),
    sa.Column('UnitPrice', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('VatRate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('RecordDate', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], ),
    sa.PrimaryKeyConstraint('ProductId')
    )
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Product_ProductId'), ['ProductId'], unique=False)

    op.create_table('Profile',
    sa.Column('ProfileId', sa.Integer(), nullable=False),
    sa.Column('ProfileName', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('RecordDate', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], ),
    sa.PrimaryKeyConstraint('ProfileId')
    )
    with op.batch_alter_table('Profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Profile_ProfileId'), ['ProfileId'], unique=False)

    op.create_table('Role',
    sa.Column('RoleId', sa.Integer(), nullable=False),
    sa.Column('RoleName', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('RecordDate', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], ),
    sa.PrimaryKeyConstraint('RoleId')
    )
    with op.batch_alter_table('Role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Role_RoleId'), ['RoleId'], unique=False)

    op.create_table('Invoice',
    sa.Column('InvoiceId', sa.Integer(), nullable=False),
    sa.Column('CustomerId', sa.Integer(), nullable=True),
    sa.Column('InvoiceNumber', sa.String(length=20), nullable=False),
    sa.Column('InvoiceDate', sa.DateTime(), nullable=True),
    sa.Column('TotalAmount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('RecordDate', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['CustomerId'], ['Customer.CustomerId'], ),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], ),
    sa.PrimaryKeyConstraint('InvoiceId')
    )
    with op.batch_alter_table('Invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Invoice_InvoiceId'), ['InvoiceId'], unique=False)

    op.create_table('ProfileRole',
    sa.Column('ProfileRoleId', sa.Integer(), nullable=False),
    sa.Column('ProfileId', sa.Integer(), nullable=False),
    sa.Column('RoleId', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('RecordDate', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ProfileId'], ['Profile.ProfileId'], ),
    sa.ForeignKeyConstraint(['RoleId'], ['Role.RoleId'], ),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], ),
    sa.PrimaryKeyConstraint('ProfileRoleId')
    )
    with op.batch_alter_table('ProfileRole', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ProfileRole_ProfileRoleId'), ['ProfileRoleId'], unique=False)

    op.create_table('UserProfile',
    sa.Column('UserProfileId', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('ProfileId', sa.Integer(), nullable=False),
    sa.Column('RecordDate', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ProfileId'], ['Profile.ProfileId'], ),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], ),
    sa.PrimaryKeyConstraint('UserProfileId')
    )
    with op.batch_alter_table('UserProfile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_UserProfile_UserProfileId'), ['UserProfileId'], unique=False)

    op.create_table('InvoiceLine',
    sa.Column('InvoiceLineId', sa.Integer(), nullable=False),
    sa.Column('InvoiceId', sa.Integer(), nullable=True),
    sa.Column('ProductId', sa.Integer(), nullable=True),
    sa.Column('ItemName', sa.String(length=100), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('Price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('RecordDate', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['InvoiceId'], ['Invoice.InvoiceId'], ),
    sa.ForeignKeyConstraint(['ProductId'], ['Product.ProductId'], ),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], ),
    sa.PrimaryKeyConstraint('InvoiceLineId')
    )
    with op.batch_alter_table('InvoiceLine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_InvoiceLine_InvoiceLineId'), ['InvoiceLineId'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('InvoiceLine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_InvoiceLine_InvoiceLineId'))

    op.drop_table('InvoiceLine')
    with op.batch_alter_table('UserProfile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_UserProfile_UserProfileId'))

    op.drop_table('UserProfile')
    with op.batch_alter_table('ProfileRole', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ProfileRole_ProfileRoleId'))

    op.drop_table('ProfileRole')
    with op.batch_alter_table('Invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Invoice_InvoiceId'))

    op.drop_table('Invoice')
    with op.batch_alter_table('Role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Role_RoleId'))

    op.drop_table('Role')
    with op.batch_alter_table('Profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Profile_ProfileId'))

    op.drop_table('Profile')
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Product_ProductId'))

    op.drop_table('Product')
    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Customer_CustomerId'))

    op.drop_table('Customer')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_UserId'))

    op.drop_table('Users')
    # ### end Alembic commands ###
